# Generated by Django 2.2.4 on 2021-02-05 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('current_price', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('delivery_charge', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('other_charge', models.DecimalField(blank=True, decimal_places=3, max_digits=99)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('status', models.CharField(default='active', max_length=50, validators=[django.core.validators.RegexValidator])),
                ('trash', models.BooleanField(default=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_id', to='category.Table')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company_id', to='company.Table')),
            ],
        ),
    ]
